<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Mocks\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Castle.Core" Version="5.2.1" />
    <PackageReference Include="FluentAssertions" Version="8.8.0" />
    <PackageReference Include="Moq" Version="4.20.70" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UStack.Identity.Application\UStack.Identity.Application.csproj" />
    <ProjectReference Include="..\UStack.Identity.Domain\UStack.Identity.Domain.csproj" />
  </ItemGroup>

</Project>
